### ISSUE TITLE
Datasheet main character

### ISSUE THREAD

**Issue by BenjaminRodot** [TheDude95100/gamejam2024#11]
## Définition du fini :
L'issue sera fermée lorsque les données pour le personnage principale seront rempli.

## Liste des données a remplir :

- [x] Editor Scripting to simplify create/balance ability later
- [x] Passive ability
- [x] Active ability
- [ ] Editor Scripting to simplify create/balance character stats later
- [x] Character stats

**Comment by maiwar** [comment]
Cut out the entity editor scripting
