### ISSUE TITLE
Caméra

### ISSUE THREAD

**Issue by BenjaminRodot** [TheDude95100/gamejam2024#27]
**Définition du fini :**
L'issue sera fermée lorsque _mettre quand la fin de l'issue_ .

Liste des tâches à réaliser :

- [ ] tâche 1
- [ ] tâche 2
- [ ] tâche 3

**Comment by GalahadIII** [comment]
Pas certain mais pas mal complet considérant que la tache était simple je vais close pour le moment a voir si des modif sont nécessaire plus tard
